# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJ_user_client',
            fields=[
                ('DJ_id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('DJ_user', models.CharField(max_length=10)),
                ('DJ_password', models.CharField(max_length=10)),
                ('DJ_email', models.CharField(max_length=50)),
                ('DJ_is_staff', models.BooleanField(default=False)),
                ('DJ_is_superuser', models.BooleanField(default=False)),
                ('DJ_is_active', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
